### ISSUE TITLE
confused

### ISSUE THREAD

**Issue by xiangdeyizhang** [imistyrain/MobileFaceNet#10]
Hi imistyrain,
    I try to compile the MobileFaceNet ,But when I make ,there is a error:main.cpp:3:22: fatal error: mropencv.h: No such file or directory,I can't find the mropencv.h,where should I find it?

Thanks

**Comment by imistyrain** [comment]
You can find it in [MRHead](https://github.com/imistyrain/MRHead), which is a cross platform opencv library link in just one click solution.
