### ISSUE TITLE
About caffe directory

### ISSUE THREAD

**Issue by xiangdeyizhang** [imistyrain/MobileFaceNet#11]
Hi imistyrai
     I try to use caffe2ncnn to change mobilefacenet.caffemodel and mobilefacenet_eploy.prototxt to ncnn model,I has some errors:
find_blob_index_by_name data failed
find_blob_index_by_name fc1 failed
Segmentation fault (core dumped)
when i change param "fc1" to "fc5",It succeed,
but it failed to output the right features like this:

check1	-903.232	-1.75775e+22
check1	-861.484	-nan
check1	-65.5987	3.14384e+38
check1	-515.687	nan
check1	115.92	nan
check1	-659.209	-nan
check1	-162.514	nan
check1	-138.998	-nan
check1	-496.864	nan
check1	-754.254	-nan
check1	-50.3096	nan
check1	-229.37	-nan
check1	817.031	nan
check1	-48.6874	inf
check1	504.314	nan
check1	-248.351	-nan
check1	1045.28	-inf
check1	972.464	nan
check1	183.73	-nan
I feel confused,can you share the origin caffemodel and protxt file with me

Thanks

**Comment by imistyrain** [comment]
The main reason is you foget to modify the input layer. You can find more information in [ncnn wiki](https://github.com/Tencent/ncnn/wiki/ncnn-%E7%BB%84%E4%BB%B6%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8C%97-alexnet)
